version: '3'

services:
  golang:
    build: .
    volumes:
      - .:/go/src/app
    tty: true
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  # mysql のサービスを追加
  mysql:
    image: mysql:5.7.22
    ports:
      - '13306:3306'

    # 日本語のデータを送った時に文字化けしてしまうので必ず必要
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/data:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_USER: golang # 使わないけど一応記述
      MYSQL_PASSWORD: golang # 使わないけど一応記述
      MYSQL_DATABASE: golang # 使わないけど一応記述
    container_name: mysql-container

